name = "dlm-notify"
main = "src/index.js"
compatibility_date = "2026-05-18"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://pdoor.github.io/DLM/"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DLM_DB"
database_name = "dlm-notify-db"
database_id = "7a6b391e-da07-45cd-a2b4-01823a1da788"
